import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import "swiper/css";
import "swiper/css/autoplay";
import "swiper/css/pagination";
import { Footer } from "@/components";

const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "CyberGear",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} overflow-x-hidden max-w-[1600px] mx-auto relative`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
